# Generated by Django 5.2.12 on 2026-04-03 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_internalnote'),
        ('core', '0002_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='core.organization'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('agent', 'Agent')], default='agent', max_length=10),
        ),
        migrations.AddField(
            model_name='cannedresponse',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canned_responses', to='core.organization'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='core.organization'),
        ),
        migrations.AddField(
            model_name='offlinemessage',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offline_messages', to='core.organization'),
        ),
    ]
