# Generated by Django 5.2.12 on 2026-04-03 13:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_chatroom_is_bookmarked_chatroom_is_snoozed_and_more'),
        ('core', '0004_organization_auto_responder_delay_and_more'),
        ('visitors', '0004_visitor_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['organization', 'status'], name='chat_chatro_organiz_0a7fdf_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['organization', '-updated_at'], name='chat_chatro_organiz_09b624_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['organization', '-created_at'], name='chat_chatro_organiz_a4d2c8_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['visitor', '-created_at'], name='chat_chatro_visitor_3da163_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['room', 'timestamp'], name='chat_messag_room_id_645da7_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['room', 'sender_type', 'is_read'], name='chat_messag_room_id_82f70f_idx'),
        ),
    ]
