# Generated by Django 5.2.12 on 2026-04-09 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_chatparticipant'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chatparticipant',
            new_name='chat_chatpa_room_id_8b04c6_idx',
            old_name='chat_chatpa_room_id_b3a6cd_idx',
        ),
    ]
