# Generated by Django 5.2.12 on 2026-04-10 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_rename_chat_chatpa_room_id_b3a6cd_idx_chat_chatpa_room_id_8b04c6_idx'),
        ('core', '0011_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_rooms', to='core.website'),
        ),
        migrations.AddField(
            model_name='offlinemessage',
            name='website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offline_messages', to='core.website'),
        ),
        migrations.CreateModel(
            name='AgentWebsiteAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website_access', to='chat.agentprofile')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_access', to='core.website')),
            ],
            options={
                'unique_together': {('agent', 'website')},
            },
        ),
    ]
