# Generated by Django 5.2.12 on 2026-05-08 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_chatroom_website_offlinemessage_website_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhook',
            name='provider',
            field=models.CharField(choices=[('generic', 'Generic JSON (raw POST)'), ('slack', 'Slack Incoming Webhook'), ('discord', 'Discord Webhook')], default='generic', max_length=20),
        ),
    ]
