# Generated by Django 5.2.12 on 2026-05-08 06:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_webhook_provider'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangelogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(blank=True, default='', help_text='Optional semver tag.', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(help_text='Markdown-ish; rendered as plain HTML in the template.')),
                ('category', models.CharField(choices=[('new', 'New Feature'), ('improved', 'Improved'), ('fixed', 'Bug Fix'), ('security', 'Security')], default='new', max_length=10)),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Changelog Entries',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='backup_codes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='totp_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='totp_secret',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='aibotconfig',
            name='api_key',
            field=models.CharField(blank=True, default='', help_text='Anthropic API key — stored per-org so each customer pays for their own usage.', max_length=200),
        ),
        migrations.AddField(
            model_name='aibotconfig',
            name='auto_summarize',
            field=models.BooleanField(default=False, help_text='When chat closes, generate a 2-line AI summary visible in the dashboard.'),
        ),
        migrations.AddField(
            model_name='aibotconfig',
            name='model_name',
            field=models.CharField(default='claude-haiku-4-5-20251001', help_text='Claude model to use. Haiku 4.5 is fast and cheap.', max_length=100),
        ),
        migrations.AddField(
            model_name='aibotconfig',
            name='provider',
            field=models.CharField(choices=[('keyword', 'Keyword / KB matching only (no LLM cost)'), ('anthropic', 'Anthropic Claude (recommended)')], default='keyword', max_length=20),
        ),
        migrations.AddField(
            model_name='aibotconfig',
            name='system_prompt',
            field=models.TextField(blank=True, default='', help_text='Optional extra instructions appended to the system prompt.'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='summary_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='summary_topics',
            field=models.CharField(blank=True, default='', help_text='Comma-separated topics extracted by the summary model.', max_length=200),
        ),
        migrations.CreateModel(
            name='MagicLinkToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='magic_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=50)),
                ('payload', models.JSONField(default=dict)),
                ('response_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True, default='')),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed (giving up after retries)')], default='pending', max_length=10)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='chat.webhook')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'next_retry_at'], name='chat_webhoo_status_8cd754_idx')],
            },
        ),
    ]
