# Generated by Django 5.2.12 on 2026-05-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_changelogentry_agentprofile_backup_codes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='totp_secret',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='aibotconfig',
            name='api_key',
            field=models.TextField(blank=True, default='', help_text='Anthropic API key — stored per-org so each customer pays for their own usage.'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='secret',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='whatsappconfig',
            name='webhook_secret',
            field=models.TextField(blank=True, default=''),
        ),
    ]
