# Generated by Django 5.2.12 on 2026-05-18 10:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_alter_agentprofile_totp_secret_and_more'),
        ('core', '0016_organization_chat_widget_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aibotconfig',
            name='api_key',
            field=models.TextField(blank=True, default='', help_text='Provider API key (Anthropic or Google AI Studio). Stored per-org so each customer pays for their own usage.'),
        ),
        migrations.AlterField(
            model_name='aibotconfig',
            name='model_name',
            field=models.CharField(default='gemini-2.0-flash', help_text='Model name. Gemini: gemini-2.0-flash (cheap+fast), gemini-2.0-pro. Claude: claude-haiku-4-5-20251001.', max_length=100),
        ),
        migrations.AlterField(
            model_name='aibotconfig',
            name='provider',
            field=models.CharField(choices=[('keyword', 'Keyword / KB matching only (no LLM cost)'), ('anthropic', 'Anthropic Claude'), ('gemini', 'Google Gemini (recommended — cheapest)')], default='keyword', max_length=20),
        ),
        migrations.CreateModel(
            name='WidgetFunnelEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('bubble_seen', 'Bubble seen'), ('panel_opened', 'Panel opened'), ('typed', 'Typed first keystroke'), ('sent', 'Message sent')], db_index=True, max_length=20)),
                ('session_key', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funnel_events', to='core.organization')),
                ('website', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funnel_events', to='core.website')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'event', 'created_at'], name='chat_widget_organiz_04c40f_idx')],
            },
        ),
    ]
