# Generated by Django 5.2.12 on 2026-05-18 10:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_alter_aibotconfig_api_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='dnd_message',
            field=models.CharField(blank=True, default='', help_text='Optional auto-reply shown to new visitors while in DND.', max_length=200),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='do_not_disturb',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ChatReopenToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('sent_to_email', models.EmailField(blank=True, default='', max_length=254)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reopen_tokens_sent', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reopen_tokens', to='chat.chatroom')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
