# Generated by Django 5.2.12 on 2026-05-19 06:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_agentprofile_dnd_message_agentprofile_do_not_disturb_and_more'),
        ('core', '0016_organization_chat_widget_hidden'),
        ('visitors', '0011_visitor_enrichment_at_visitor_enrichment_company_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMailbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Label shown in dashboard (e.g. "Support", "Sales")', max_length=100)),
                ('is_enabled', models.BooleanField(default=True)),
                ('imap_host', models.CharField(help_text='e.g. imap.gmail.com', max_length=200)),
                ('imap_port', models.PositiveIntegerField(default=993)),
                ('imap_use_ssl', models.BooleanField(default=True)),
                ('imap_username', models.CharField(max_length=200)),
                ('imap_password', models.TextField(blank=True, default='', help_text='Fernet-encrypted at rest. For Gmail use an App Password.')),
                ('imap_folder', models.CharField(default='INBOX', max_length=100)),
                ('last_polled_uid', models.PositiveBigIntegerField(default=0, help_text='Tracks the highest IMAP UID we have ingested.')),
                ('last_polled_at', models.DateTimeField(blank=True, null=True)),
                ('smtp_host', models.CharField(help_text='e.g. smtp.gmail.com', max_length=200)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('smtp_username', models.CharField(max_length=200)),
                ('smtp_password', models.TextField(blank=True, default='')),
                ('from_email', models.EmailField(help_text='Reply-from address shown to the customer.', max_length=254)),
                ('from_name', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Email Mailboxes',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='chatroom',
            name='channel',
            field=models.CharField(choices=[('widget', 'Web Widget'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS')], db_index=True, default='widget', max_length=20),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='coach_feedback',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='external_thread_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='message',
            name='msg_type',
            field=models.CharField(choices=[('text', 'Text'), ('file', 'File'), ('image', 'Image'), ('system', 'System'), ('booking', 'Booking card (Calendly / Cal.com)')], default='text', max_length=10),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['organization', 'channel', 'status'], name='chat_chatro_organiz_53c46d_idx'),
        ),
        migrations.AddField(
            model_name='emailmailbox',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_mailboxes', to='core.organization'),
        ),
        migrations.AddField(
            model_name='emailmailbox',
            name='website',
            field=models.ForeignKey(blank=True, help_text='Optional — pin this mailbox to one website. Leave blank for org-wide.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_mailboxes', to='core.website'),
        ),
    ]
