# Generated by Django 5.2.12 on 2026-05-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_emailmailbox_chatroom_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='agent_language',
            field=models.CharField(blank=True, default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='auto_translate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='visitor_language',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='message',
            name='translated_content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='message',
            name='translated_to',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
