# Generated by Django 5.2.12 on 2026-05-19 08:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0019_chatroom_agent_language_chatroom_auto_translate_and_more'),
        ('core', '0016_organization_chat_widget_hidden'),
        ('visitors', '0012_visitor_identified_at_visitor_identified_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['organization', 'status', '-updated_at'], name='chat_chatro_organiz_e516db_idx'),
        ),
    ]
