# Generated by Django 5.2.12 on 2026-03-31 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='My Website', max_length=200)),
                ('welcome_message', models.TextField(default='Hi! How can we help you today?')),
                ('offline_message', models.TextField(default='We are currently offline. Please leave a message.')),
                ('chat_widget_color', models.CharField(default='#6366f1', max_length=7)),
                ('auto_reply_enabled', models.BooleanField(default=True)),
                ('auto_reply_message', models.TextField(default='Thanks for reaching out! An agent will be with you shortly.')),
                ('require_email', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Website Settings',
            },
        ),
    ]
