# Generated by Django 5.2.12 on 2026-04-03 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('widget_key', models.CharField(db_index=True, max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('widget_title', models.CharField(default='LiveTrack Support', max_length=100)),
                ('widget_color', models.CharField(default='#7c3aed', max_length=7)),
                ('widget_position', models.CharField(choices=[('bottom-right', 'Bottom Right'), ('bottom-left', 'Bottom Left')], default='bottom-right', max_length=20)),
                ('welcome_message', models.TextField(default='Hi! How can we help you today?')),
                ('offline_message', models.TextField(default='We are currently offline. Please leave a message.')),
                ('auto_reply_enabled', models.BooleanField(default=True)),
                ('auto_reply_message', models.TextField(default='An agent will be with you shortly.')),
                ('require_email', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_organizations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
