# Generated by Django 5.2.12 on 2026-04-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='business_hours_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='business_hours_end',
            field=models.TimeField(default='18:00'),
        ),
        migrations.AddField(
            model_name='organization',
            name='business_hours_start',
            field=models.TimeField(default='09:00'),
        ),
        migrations.AddField(
            model_name='organization',
            name='business_hours_timezone',
            field=models.CharField(default='Asia/Kolkata', max_length=50),
        ),
        migrations.AddField(
            model_name='organization',
            name='notify_email',
            field=models.EmailField(blank=True, default='', help_text='Email for new chat notifications', max_length=254),
        ),
        migrations.AddField(
            model_name='organization',
            name='notify_on_new_chat',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='proactive_delay',
            field=models.PositiveIntegerField(default=30, help_text='Seconds before showing proactive message'),
        ),
        migrations.AddField(
            model_name='organization',
            name='proactive_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='proactive_message',
            field=models.CharField(default='Need help? Chat with us!', max_length=200),
        ),
    ]
