# Generated by Django 5.2.12 on 2026-04-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_organization_business_hours_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='auto_responder_delay',
            field=models.PositiveIntegerField(default=2, help_text='Minutes before auto-response'),
        ),
        migrations.AddField(
            model_name='organization',
            name='auto_responder_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='auto_responder_message',
            field=models.TextField(default='Thanks for waiting! An agent will be with you very soon.'),
        ),
        migrations.AddField(
            model_name='organization',
            name='chat_assign_rule',
            field=models.CharField(choices=[('least_busy', 'Least Busy'), ('round_robin', 'Round Robin'), ('manual', 'Manual Only')], default='least_busy', max_length=20),
        ),
    ]
