# Generated by Django 5.2.12 on 2026-04-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_organization_allowed_domains_and_blocked_countries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='widget_title',
            field=models.CharField(default='LiveVisitorHub Support', max_length=100),
        ),
    ]
