# Generated by Django 5.2.12 on 2026-04-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_organization_widget_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='attack_mode_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='attack_mode_message',
            field=models.TextField(default='High traffic detected. Please try again in a minute.'),
        ),
    ]
