# Generated by Django 5.2.12 on 2026-04-10 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_organization_attack_mode_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('domain', models.CharField(help_text='Primary domain, e.g. example.com', max_length=253)),
                ('tracking_key', models.CharField(db_index=True, max_length=32, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='websites', to='core.organization')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('organization', 'domain')},
            },
        ),
    ]
