# Generated by Django 5.2.12 on 2026-04-10 06:26

from django.db import migrations


def backfill_websites(apps, schema_editor):
    """Create a Website for each existing Organization, backfill all FKs."""
    Organization = apps.get_model('core', 'Organization')
    Website = apps.get_model('core', 'Website')
    Visitor = apps.get_model('visitors', 'Visitor')
    CustomEvent = apps.get_model('visitors', 'CustomEvent')
    SessionRecording = apps.get_model('visitors', 'SessionRecording')
    ClickData = apps.get_model('visitors', 'ClickData')
    ScrollData = apps.get_model('visitors', 'ScrollData')
    JSError = apps.get_model('visitors', 'JSError')
    FrustrationSignal = apps.get_model('visitors', 'FrustrationSignal')
    PageInsight = apps.get_model('visitors', 'PageInsight')
    ChatRoom = apps.get_model('chat', 'ChatRoom')
    OfflineMessage = apps.get_model('chat', 'OfflineMessage')
    AgentProfile = apps.get_model('chat', 'AgentProfile')
    AgentWebsiteAccess = apps.get_model('chat', 'AgentWebsiteAccess')

    for org in Organization.objects.all():
        # Derive domain from allowed_domains or slug
        domain = ''
        if org.allowed_domains:
            parts = [d.strip() for d in org.allowed_domains.replace('\n', ',').split(',') if d.strip()]
            if parts:
                domain = parts[0]
        if not domain:
            domain = f'{org.slug}.example.com'

        # Create website using org's existing widget_key so embeds keep working
        website = Website.objects.create(
            organization=org,
            name=org.name,
            domain=domain,
            tracking_key=org.widget_key,
            is_active=True,
        )

        # Backfill all models
        Visitor.objects.filter(organization=org, website__isnull=True).update(website=website)
        CustomEvent.objects.filter(organization=org, website__isnull=True).update(website=website)
        SessionRecording.objects.filter(organization=org, website__isnull=True).update(website=website)
        ClickData.objects.filter(organization=org, website__isnull=True).update(website=website)
        ScrollData.objects.filter(organization=org, website__isnull=True).update(website=website)
        JSError.objects.filter(organization=org, website__isnull=True).update(website=website)
        FrustrationSignal.objects.filter(organization=org, website__isnull=True).update(website=website)
        PageInsight.objects.filter(organization=org, website__isnull=True).update(website=website)
        ChatRoom.objects.filter(organization=org, website__isnull=True).update(website=website)
        OfflineMessage.objects.filter(organization=org, website__isnull=True).update(website=website)

        # Grant all existing agents access to this website
        for agent in AgentProfile.objects.filter(organization=org):
            AgentWebsiteAccess.objects.get_or_create(agent=agent, website=website)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_website'),
        ('visitors', '0009_clickdata_website_customevent_website_and_more'),
        ('chat', '0012_chatroom_website_offlinemessage_website_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_websites, migrations.RunPython.noop),
    ]
