# Generated by Django 5.2.12 on 2026-04-10 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_backfill_websites'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='offline_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='website',
            name='welcome_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='website',
            name='widget_color',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AddField(
            model_name='website',
            name='widget_position',
            field=models.CharField(blank=True, choices=[('', 'Use Default'), ('bottom-right', 'Bottom Right'), ('bottom-left', 'Bottom Left')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='website',
            name='widget_title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
