# Generated by Django 5.2.12 on 2026-04-13 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_website_offline_message_website_welcome_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='approval_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='approved', max_length=10),
        ),
        migrations.AddField(
            model_name='website',
            name='is_auto_detected',
            field=models.BooleanField(default=False, help_text='Was this domain auto-detected?'),
        ),
        migrations.AddField(
            model_name='website',
            name='notify_email_override',
            field=models.EmailField(blank=True, default='', help_text='Override org notify email for this site', max_length=254),
        ),
        migrations.AddField(
            model_name='website',
            name='notify_error',
            field=models.BooleanField(default=False, help_text='Email on JS error spike'),
        ),
        migrations.AddField(
            model_name='website',
            name='notify_new_chat',
            field=models.BooleanField(default=True, help_text='Email on new chat'),
        ),
        migrations.AddField(
            model_name='website',
            name='notify_new_visitor',
            field=models.BooleanField(default=False, help_text='Email on new visitor'),
        ),
        migrations.AddField(
            model_name='website',
            name='notify_offline_msg',
            field=models.BooleanField(default=True, help_text='Email on offline message'),
        ),
        migrations.AddField(
            model_name='website',
            name='script_last_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='script_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='WebsiteGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#6366f1', help_text='Hex color for the tag', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website_groups', to='core.organization')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.AddField(
            model_name='website',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='websites', to='core.websitegroup'),
        ),
    ]
