# Generated by Django 5.2.12 on 2026-05-08 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_website_approval_status_website_is_auto_detected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='prechat_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='prechat_intro',
            field=models.CharField(default='Tell us a bit about yourself before we begin.', max_length=300),
        ),
        migrations.AddField(
            model_name='organization',
            name='prechat_require_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='prechat_require_name',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='prechat_require_phone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='prechat_require_subject',
            field=models.BooleanField(default=False),
        ),
    ]
