# Generated by Django 5.2.12 on 2026-05-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_organization_prechat_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='chat_widget_hidden',
            field=models.BooleanField(default=False, help_text='Hide the chat bubble on customer sites. Visitor tracking and recordings stay active.'),
        ),
    ]
