# Generated by Django 5.2.12 on 2026-03-31 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
    ]
