# Generated by Django 5.2.12 on 2026-04-03 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_organization'),
        ('visitors', '0002_visitor_is_banned'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='session_key',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='visitor',
            unique_together={('session_key', 'organization')},
        ),
    ]
