# Generated by Django 5.2.12 on 2026-04-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0003_visitor_organization_alter_visitor_session_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='score',
            field=models.PositiveIntegerField(default=0, help_text='Visitor engagement score'),
        ),
    ]
