# Generated by Django 5.2.12 on 2026-04-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_organization_auto_responder_delay_and_more'),
        ('visitors', '0004_visitor_score'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['visitor', '-timestamp'], name='visitors_pa_visitor_a6ae4d_idx'),
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['-last_seen'], name='visitors_vi_last_se_8f3494_idx'),
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['organization', '-last_seen'], name='visitors_vi_organiz_7ecbd6_idx'),
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['organization', 'is_banned'], name='visitors_vi_organiz_cc4ba1_idx'),
        ),
    ]
