# Generated by Django 5.2.12 on 2026-04-06 06:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_organization_auto_responder_delay_and_more'),
        ('visitors', '0005_pageview_visitors_pa_visitor_a6ae4d_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(db_index=True, max_length=200)),
                ('event_category', models.CharField(blank=True, default='', max_length=200)),
                ('event_label', models.CharField(blank=True, default='', max_length=500)),
                ('event_value', models.FloatField(default=0)),
                ('page_url', models.URLField(blank=True, default='', max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('goal_type', models.CharField(choices=[('pageview', 'Page View (URL match)'), ('event', 'Custom Event'), ('duration', 'Session Duration'), ('pages', 'Pages Per Session')], default='pageview', max_length=20)),
                ('target_url', models.CharField(blank=True, default='', help_text='URL pattern to match for pageview goals', max_length=500)),
                ('target_event', models.CharField(blank=True, default='', help_text='Event name for event goals', max_length=200)),
                ('target_value', models.FloatField(default=0, help_text='Duration (seconds) or pages count threshold')),
                ('monetary_value', models.FloatField(default=0, help_text='Value of each conversion in currency')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoalCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.URLField(blank=True, default='', max_length=500)),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly (Monday)'), ('monthly', 'Monthly (1st)')], default='weekly', max_length=10)),
                ('include_visitors', models.BooleanField(default=True)),
                ('include_chats', models.BooleanField(default=True)),
                ('include_goals', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sent', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='pageview',
            name='is_entry',
            field=models.BooleanField(default=False, help_text='Is this the landing/entry page'),
        ),
        migrations.AddField(
            model_name='pageview',
            name='is_exit',
            field=models.BooleanField(default=False, help_text='Is this the exit page'),
        ),
        migrations.AddField(
            model_name='pageview',
            name='load_time_ms',
            field=models.PositiveIntegerField(default=0, help_text='Page load time in milliseconds'),
        ),
        migrations.AddField(
            model_name='pageview',
            name='utm_campaign',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='pageview',
            name='utm_medium',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='pageview',
            name='utm_source',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='visitor',
            name='exit_page',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='visitor',
            name='is_bounced',
            field=models.BooleanField(default=False, help_text='Visited only 1 page'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='landing_page',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='visitor',
            name='language',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='visitor',
            name='pages_per_session',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='visitor',
            name='session_duration',
            field=models.PositiveIntegerField(default=0, help_text='Total session duration in seconds'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='utm_campaign',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='visitor',
            name='utm_content',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='visitor',
            name='utm_medium',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='visitor',
            name='utm_source',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='visitor',
            name='utm_term',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['-timestamp'], name='visitors_pa_timesta_185b2d_idx'),
        ),
        migrations.AddField(
            model_name='customevent',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_events', to='core.organization'),
        ),
        migrations.AddField(
            model_name='customevent',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='visitors.visitor'),
        ),
        migrations.AddField(
            model_name='goal',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='core.organization'),
        ),
        migrations.AddField(
            model_name='goalcompletion',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='visitors.goal'),
        ),
        migrations.AddField(
            model_name='goalcompletion',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_completions', to='visitors.visitor'),
        ),
        migrations.AddField(
            model_name='scheduledreport',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_reports', to='core.organization'),
        ),
        migrations.AddIndex(
            model_name='customevent',
            index=models.Index(fields=['organization', 'event_name', '-timestamp'], name='visitors_cu_organiz_34e1b5_idx'),
        ),
        migrations.AddIndex(
            model_name='customevent',
            index=models.Index(fields=['visitor', '-timestamp'], name='visitors_cu_visitor_e0f8da_idx'),
        ),
        migrations.AddIndex(
            model_name='goalcompletion',
            index=models.Index(fields=['goal', '-completed_at'], name='visitors_go_goal_id_5cba16_idx'),
        ),
    ]
