# Generated by Django 5.2.12 on 2026-04-06 07:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_organization_auto_responder_delay_and_more'),
        ('visitors', '0006_customevent_goal_goalcompletion_scheduledreport_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('events_data', models.JSONField(default=list, help_text='Array of recorded DOM events')),
                ('duration', models.PositiveIntegerField(default=0, help_text='Recording duration in seconds')),
                ('pages_visited', models.PositiveIntegerField(default=0)),
                ('start_url', models.URLField(blank=True, default='', max_length=500)),
                ('device_type', models.CharField(blank=True, default='', max_length=20)),
                ('screen_width', models.PositiveIntegerField(default=0)),
                ('screen_height', models.PositiveIntegerField(default=0)),
                ('has_rage_clicks', models.BooleanField(default=False)),
                ('has_dead_clicks', models.BooleanField(default=False)),
                ('has_quick_back', models.BooleanField(default=False)),
                ('has_errors', models.BooleanField(default=False)),
                ('frustration_score', models.PositiveIntegerField(default=0, help_text='0-100 frustration level')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_recordings', to='core.organization')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='visitors.visitor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JSError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_message', models.TextField()),
                ('error_source', models.CharField(blank=True, default='', max_length=500)),
                ('error_line', models.PositiveIntegerField(default=0)),
                ('error_col', models.PositiveIntegerField(default=0)),
                ('stack_trace', models.TextField(blank=True, default='')),
                ('page_url', models.URLField(blank=True, default='', max_length=500)),
                ('browser', models.CharField(blank=True, default='', max_length=100)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='js_errors', to='core.organization')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='js_errors', to='visitors.visitor')),
                ('recording', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='errors', to='visitors.sessionrecording')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FrustrationSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(choices=[('rage_click', 'Rage Click'), ('dead_click', 'Dead Click'), ('quick_back', 'Quick Back'), ('excessive_scroll', 'Excessive Scrolling'), ('error_click', 'Click After Error')], max_length=20)),
                ('page_url', models.URLField(blank=True, default='', max_length=500)),
                ('page_path', models.CharField(blank=True, default='', max_length=500)),
                ('element_selector', models.CharField(blank=True, default='', max_length=500)),
                ('element_text', models.CharField(blank=True, default='', max_length=200)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frustration_signals', to='core.organization')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frustration_signals', to='visitors.visitor')),
                ('recording', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frustration_signals', to='visitors.sessionrecording')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ClickData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.URLField(max_length=500)),
                ('page_path', models.CharField(blank=True, default='', max_length=500)),
                ('x_percent', models.FloatField(help_text='Click X position as % of viewport width')),
                ('y_percent', models.FloatField(help_text='Click Y position as % of page height')),
                ('x_px', models.PositiveIntegerField(default=0)),
                ('y_px', models.PositiveIntegerField(default=0)),
                ('element_tag', models.CharField(blank=True, default='', max_length=50)),
                ('element_text', models.CharField(blank=True, default='', max_length=200)),
                ('element_selector', models.CharField(blank=True, default='', max_length=500)),
                ('click_type', models.CharField(choices=[('click', 'Normal Click'), ('rage', 'Rage Click'), ('dead', 'Dead Click')], default='click', max_length=10)),
                ('device_type', models.CharField(blank=True, default='desktop', max_length=20)),
                ('viewport_width', models.PositiveIntegerField(default=0)),
                ('viewport_height', models.PositiveIntegerField(default=0)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='click_data', to='core.organization')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='visitors.visitor')),
                ('recording', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clicks', to='visitors.sessionrecording')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PageInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_path', models.CharField(db_index=True, max_length=500)),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('unique_visitors', models.PositiveIntegerField(default=0)),
                ('avg_time_spent', models.FloatField(default=0)),
                ('avg_scroll_depth', models.FloatField(default=0)),
                ('bounce_rate', models.FloatField(default=0)),
                ('total_clicks', models.PositiveIntegerField(default=0)),
                ('rage_clicks', models.PositiveIntegerField(default=0)),
                ('dead_clicks', models.PositiveIntegerField(default=0)),
                ('frustration_score', models.FloatField(default=0)),
                ('engagement_score', models.FloatField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_insights', to='core.organization')),
            ],
            options={
                'ordering': ['-total_views'],
                'unique_together': {('organization', 'page_path')},
            },
        ),
        migrations.CreateModel(
            name='ScrollData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.URLField(max_length=500)),
                ('page_path', models.CharField(blank=True, default='', max_length=500)),
                ('max_scroll_percent', models.PositiveIntegerField(default=0, help_text='Max scroll depth 0-100%')),
                ('page_height', models.PositiveIntegerField(default=0)),
                ('viewport_height', models.PositiveIntegerField(default=0)),
                ('device_type', models.CharField(blank=True, default='desktop', max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scroll_data', to='core.organization')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrolls', to='visitors.visitor')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['organization', 'page_path', '-timestamp'], name='visitors_sc_organiz_eca673_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='sessionrecording',
            index=models.Index(fields=['organization', '-created_at'], name='visitors_se_organiz_e7a5f9_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionrecording',
            index=models.Index(fields=['frustration_score'], name='visitors_se_frustra_ee51b1_idx'),
        ),
        migrations.AddIndex(
            model_name='jserror',
            index=models.Index(fields=['organization', '-timestamp'], name='visitors_js_organiz_95c99b_idx'),
        ),
        migrations.AddIndex(
            model_name='frustrationsignal',
            index=models.Index(fields=['organization', 'signal_type', '-timestamp'], name='visitors_fr_organiz_71b9e8_idx'),
        ),
        migrations.AddIndex(
            model_name='clickdata',
            index=models.Index(fields=['organization', 'page_path', '-timestamp'], name='visitors_cl_organiz_8ef4a0_idx'),
        ),
        migrations.AddIndex(
            model_name='clickdata',
            index=models.Index(fields=['click_type'], name='visitors_cl_click_t_73862f_idx'),
        ),
    ]
