# Generated by Django 5.2.12 on 2026-04-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0007_sessionrecording_jserror_frustrationsignal_clickdata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='visitor_fingerprint',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
    ]
