# Generated by Django 5.2.12 on 2026-04-10 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_website'),
        ('visitors', '0008_visitor_visitor_fingerprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='clickdata',
            name='website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='click_data', to='core.website'),
        ),
        migrations.AddField(
            model_name='customevent',
            name='website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_events', to='core.website'),
        ),
        migrations.AddField(
            model_name='frustrationsignal',
            name='website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frustration_signals', to='core.website'),
        ),
        migrations.AddField(
            model_name='jserror',
            name='website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='js_errors', to='core.website'),
        ),
        migrations.AddField(
            model_name='pageinsight',
            name='website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_insights', to='core.website'),
        ),
        migrations.AddField(
            model_name='scrolldata',
            name='website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scroll_data', to='core.website'),
        ),
        migrations.AddField(
            model_name='sessionrecording',
            name='website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_recordings', to='core.website'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitors', to='core.website'),
        ),
    ]
