# Generated by Django 5.2.12 on 2026-05-01 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_website_approval_status_website_is_auto_detected_and_more'),
        ('visitors', '0009_clickdata_website_customevent_website_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['organization', 'visitor_fingerprint'], name='visitors_vi_organiz_f2d84f_idx'),
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['website', '-last_seen'], name='visitors_vi_website_9ba413_idx'),
        ),
    ]
