# Generated by Django 5.2.12 on 2026-05-19 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0010_visitor_visitors_vi_organiz_f2d84f_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='enrichment_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='enrichment_company',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='visitor',
            name='enrichment_role',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='visitor',
            name='enrichment_summary',
            field=models.TextField(blank=True, default='', help_text='Brief AI-generated visitor summary.'),
        ),
    ]
