# Generated by Django 5.2.12 on 2026-05-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0011_visitor_enrichment_at_visitor_enrichment_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='identified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='identified_email',
            field=models.EmailField(blank=True, db_index=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='visitor',
            name='identified_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='visitor',
            name='identified_user_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='visitor',
            name='traits',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
