# Generated by Django 5.2.12 on 2026-05-19 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_organization_chat_widget_hidden'),
        ('visitors', '0012_visitor_identified_at_visitor_identified_email_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='clickdata',
            index=models.Index(fields=['organization', '-timestamp'], name='visitors_cl_organiz_b4ef46_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['url', '-timestamp'], name='visitors_pa_url_2a4bae_idx'),
        ),
    ]
